name: EKS CD

on:
  workflow_call:
    inputs:
      aws_account_id:
        description: 'AWS Account ID'
        required: true
        type: string
      env:
        description: 'Environment'
        default: dev
        required: false
        type: string
      image_tag:
        description: "The version tag of Docker image to be downloaded."
        required: false
        type: string
      aws_ecr:
        description: "Name of AWS Container Registry"
        type: string
        required: false
      aws_ecr_namespace:
        description: "AWS Container Registry Namespace"
        default: wtv_ns
        type: string
        required: false
      aws_region:
        default: us-east-1
        description: "AWS Region"
        type: string
        required: false
      cluster_name:
        default: wtv-cluster
        description: "EKS cluster name"
        type: string
        required: true


jobs:

  deploy:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
      id-token: write
      checks: write
      issues: read
      pull-requests: write

    steps:

      # Checkout
      - name: Checkout
        uses: actions/checkout@v4

      # Authenticate to AWS
      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::${{ inputs.aws_account_id }}:role/dev-wtv-github-actions-role
          aws-region: ${{ inputs.aws_region }}

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig \
            --region ${{ inputs.aws_region }} \
            --name ${{ inputs.env }}-${{ inputs.cluster_name }} \
            --role-arn arn:aws:iam::${{ inputs.aws_account_id }}:role/dev-wtv-github-actions-role

      - name: Check kubectl context
        run: |
          kubectl config get-contexts
          kubectl get nodes

      - name: Fetch secrets from AWS Secrets Manager
        id: secrets
        run: |
          SECRET_JSON=$(aws secretsmanager get-secret-value --secret-id /wtv/${{ inputs.env }}/db --query SecretString --output text)
          echo "$SECRET_JSON" | jq -r 'to_entries[] | "\(.key)=\(.value)"' > .env
          cat .env

      - name: Helm install
        run: | 
          helm install nginx ./helm/nginx --namespace ${{ inputs.env }} --create-namespace